/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.BankAccountDao;
import java.util.Scanner;
import javax.swing.JOptionPane;
import model.BankAccount;


/**
 *
 * @author Kwize
 */
public class CoreBanking extends javax.swing.JFrame {

    BankAccountDao daop=new BankAccountDao();
    private boolean isEditing = false;

    /**
     * Creates new form CoreBanking
     */
    Scanner sc= new Scanner(System.in);
    public CoreBanking() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        bankAccountNumberText = new javax.swing.JTextField();
        bankAccountNameText = new javax.swing.JTextField();
        bankAccountTypeText = new javax.swing.JTextField();
        amountText = new javax.swing.JTextField();
        registerButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        DeleteButton = new javax.swing.JButton();
        SearchButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("REGISTER BANK ACCOUNT FORM");

        jLabel2.setText("Bank Account number");

        jLabel3.setText("Bank Account name");

        jLabel4.setText("Bank Account Type");

        jLabel5.setText("Bank Account balance");



        // METHOD ENSURING THAT ALL THE FIELDS ARE EMPTIED AFTER THE OPERATION



        bankAccountNameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bankAccountNameTextActionPerformed(evt);
            }
        });

        amountText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amountTextActionPerformed(evt);
            }
        });

        registerButton.setText("REGISTER");
        registerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        DeleteButton.setText("DELETE");
        DeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteButtonActionPerformed(evt);
            }
        });


        SearchButton.setText("SEARCH");
        SearchButton.setText("SEARCH");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });


        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(registerButton)
                                .addGap(18, 18, 18)
                                .addComponent(UpdateButton)))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DeleteButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SearchButton))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(bankAccountNumberText, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                        .addComponent(bankAccountNameText))
                                    .addComponent(bankAccountTypeText, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(180, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(bankAccountNumberText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(bankAccountNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(bankAccountTypeText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(amountText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerButton)
                    .addComponent(UpdateButton)
                    .addComponent(DeleteButton)
                    .addComponent(SearchButton))
                .addContainerGap(230, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bankAccountNameTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bankAccountNameTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bankAccountNameTextActionPerformed

    private void amountTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amountTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_amountTextActionPerformed






    private void clearFields() {
        bankAccountNumberText.setText("");
        bankAccountNameText.setText("");
        bankAccountTypeText.setText("");
        amountText.setText("");
        // Make fields editable again if you disabled them
        bankAccountNumberText.setEditable(true);
        bankAccountNameText.setEditable(true);
        bankAccountTypeText.setEditable(true);
        amountText.setEditable(true);
    }








    private void registerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerButtonActionPerformed
        BankAccount theAccount=new BankAccount();
        theAccount.setAccountName(bankAccountNameText.getText());
        theAccount.setAccountNumber(bankAccountNumberText.getText());
        theAccount.setAccountType(bankAccountTypeText.getText());
        double amount=Double.parseDouble(amountText.getText());
        theAccount.setAmount(amount);
        //SENDING DATA TO DAO
        BankAccountDao dao=new BankAccountDao();
        int rowAffected =dao.createBankAccount(theAccount);
        if(rowAffected>0){
        JOptionPane.showMessageDialog(null, "Data saved successfully");
        clearFields();
        }
        else{
            JOptionPane.showMessageDialog(null, "Data NOT saved successfully"); 
        }
    
        
                // TODO add your handling code here:
                
    }//GEN-LAST:event_registerButtonActionPerformed


    // THE DELETE BUTTON OPERATINS
    private void DeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // 1️⃣ Prompt user to enter account number
        String accNum = JOptionPane.showInputDialog(this, "Enter Account Number to delete:");

        if (accNum == null || accNum.trim().isEmpty()) {
            // User pressed Cancel or entered nothing
            return;
        }

        // 2️⃣ Check if account exists
        BankAccount account = daop.getAccountByNumber(accNum);
        if (account == null) {
            JOptionPane.showMessageDialog(this, "Account not found.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // 3️⃣ Show details in read-only fields
        bankAccountNumberText.setText(account.getAccountNumber());
        bankAccountNameText.setText(account.getAccountName());
        bankAccountTypeText.setText(account.getAccountType());
        amountText.setText(String.valueOf(account.getAmount()));

        bankAccountNumberText.setEditable(false);
        bankAccountNameText.setEditable(false);
        bankAccountTypeText.setEditable(false);
        amountText.setEditable(false);

        // 4️⃣ Confirm deletion
        int confirm = JOptionPane.showConfirmDialog(this,
                "Are you sure you want to delete this account?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            int result = daop.deleteAccount(accNum);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "Account successfully deleted.");
                // Clear fields
                bankAccountNumberText.setText("");
                bankAccountNameText.setText("");
                bankAccountTypeText.setText("");
                amountText.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete account. Please try again.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // User clicked No
            JOptionPane.showMessageDialog(this, "Deletion canceled.");
        }
    }



    // SEARCH BUTTON
    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Prompt user for account number
        String accNum = JOptionPane.showInputDialog(this, "Enter Account Number to search:");

        if (accNum == null || accNum.trim().isEmpty()) {
            // User pressed Cancel or entered nothing
            return;
        }

        // Check if account exists
        BankAccount account = daop.getAccountByNumber(accNum);
        if (account == null) {
            JOptionPane.showMessageDialog(this, "Account not found.", "Error", JOptionPane.ERROR_MESSAGE);
            // Clear any previous data
            bankAccountNumberText.setText("");
            bankAccountNameText.setText("");
            bankAccountTypeText.setText("");
            amountText.setText("");
            return;
        }

        // Show details in text fields
        bankAccountNumberText.setText(account.getAccountNumber());
        bankAccountNameText.setText(account.getAccountName());
        bankAccountTypeText.setText(account.getAccountType());
        amountText.setText(String.valueOf(account.getAmount()));

        // Optionally make fields editable if you plan to update later
        bankAccountNumberText.setEditable(false);
        bankAccountNameText.setEditable(true);
        bankAccountTypeText.setEditable(true);
        amountText.setEditable(true);

        JOptionPane.showMessageDialog(this, "Account found.");
    }





    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isEditing) {
            // Step 1️⃣: Load account for editing
            String accNum = JOptionPane.showInputDialog(this, "Enter Account Number to update:");
            if (accNum == null || accNum.trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Update cancelled: No account number entered.");
                return;
            }

            BankAccount account = daop.getAccountByNumber(accNum.trim());
            if (account == null) {
                JOptionPane.showMessageDialog(this, "❌ Account not found.");
                return;
            }

            // Populate fields
            bankAccountNumberText.setText(account.getAccountNumber());
            bankAccountNameText.setText(account.getAccountName());
            bankAccountTypeText.setText(account.getAccountType());
            amountText.setText(String.valueOf(account.getAmount()));
            bankAccountNumberText.setEditable(false);

            // Let user edit the fields
            JOptionPane.showMessageDialog(this, "Account found. Edit the details in the fields, then click UPDATE again to save changes.");
            isEditing = true; // switch to save mode
        } else {
            // Step 2️⃣: Save changes
            BankAccount account = daop.getAccountByNumber(bankAccountNumberText.getText().trim());
            if (account == null) {
                JOptionPane.showMessageDialog(this, "❌ Account not found. Cannot update.");
                isEditing = false;
                return;
            }

            String newName = bankAccountNameText.getText().trim();
            String newType = bankAccountTypeText.getText().trim();
            double newAmount;
            try {
                newAmount = Double.parseDouble(amountText.getText().trim());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "❌ Invalid amount. Update failed.");
                return;
            }

            // Update account
            account.setAccountName(newName);
            account.setAccountType(newType);
            account.setAmount(newAmount);

            int result = daop.updateAccount(account);
            if (result > 0) {
                JOptionPane.showMessageDialog(this, "✅ Account updated successfully!");
                clearFields();
            } else {
                JOptionPane.showMessageDialog(this, "❌ Failed to update account.");
            }

            // Reset
            bankAccountNumberText.setEditable(true);
            bankAccountNumberText.setText("");
            bankAccountNameText.setText("");
            bankAccountTypeText.setText("");
            amountText.setText("");
            isEditing = false;
        }
    }

//GEN-LAST:event_UpdateButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoreBanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoreBanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoreBanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoreBanking.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoreBanking().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DeleteButton;
    private javax.swing.JButton SearchButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField amountText;
    private javax.swing.JTextField bankAccountNameText;
    private javax.swing.JTextField bankAccountNumberText;
    private javax.swing.JTextField bankAccountTypeText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton registerButton;
    // End of variables declaration//GEN-END:variables
}
